version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=todo_list
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - DB_HOST=database
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_NAME=todo_list
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    restart: always
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data:
